variable "name"                  { }
variable "vpc_cidr"              { }
variable "vpc_cidrs_public"      { }
variable "vpc_cidrs_private"     { }
variable "environment"           { }
variable "os"                    { }
variable "os_version"            { }
variable "consul_version"        { }
variable "vault_version"         { }
variable "nomad_version"         { }
variable "ssh_key_name"          { }
variable "bastion_instance_type" { }
